<?php

/**
* Arquivo: login.phtml (UTF-8)
*
* Data: 17/10/2014
* @author André Luis Rocha Menutole <andre.rocha@superpay.com.br>
*/
?>
<form action="login/login/acao/logar" method="post">
    <p>
        <label>Login:</label>
        <input type="text" name="login" />
    </p>
    <p>
        <label>Senha:</label>
        <input type="password" name="senha" />
    </p>
    <input type="submit" value="logar" />
</form>