<?php

/**
* Arquivo: novo.phtml (UTF-8)
*
* Data: 16/10/2014
* @author André Luis Rocha Menutole <andre.rocha@superpay.com.br>
*/
?>
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div>View - Produtos Novos</div>
    </body>
</html>
